### ISSUE TITLE
No popup under sublime 3.2.1 (build 3207)

### ISSUE THREAD

**Issue by wingsline** [gh640/SublimeComposerPackageInfo#2]
Was working before, but with Sublime 3.2.1 stopped showing the popup. No error messages in console, nothing.

**Comment by gh640** [comment]
Thanks for sharing the issue. I confirmed that.

It seems that the cause is the change of the scope names this package depends on to detect Composer package names in `composer.json` files:

- [JSON color scheme broken - Technical Support - Sublime Forum](https://forum.sublimetext.com/t/json-color-scheme-broken/43312/4)
- [Rainbow colors by JSON object level with any color scheme - General Discussion - Sublime Forum](https://forum.sublimetext.com/t/rainbow-colors-by-json-object-level-with-any-color-scheme/42968/2)

I tried adjusting the code to support the latest Sublime Text 3.2.1 and made a new release `1.4.0`. It works in my environment but could you please check it (once the new version gets available)? Thanks :D

**Comment by wingsline** [comment]
It is working, thank you for the quick fix!

**Comment by gh640** [comment]
Great. Thanks!
